### PR TITLE
Add link to my fork for a maintained version.

### PR DESCRIPTION
**Pull request by harmo**

### CODE REVIEW

**Comment by harmo** [comment]
@tomchristie Thanks !
Now how can I do to push my bumped version on pypi ?
(not allowed to store 'django-email-as-username' package information)

**Comment by tomchristie** [comment]
Diff package name I guess.

**Comment by harmo** [comment]
You can't add me with maintainer role on pypi ?

**Comment by tomchristie** [comment]
I could, but we'd probably like to leave the current state of the package as-is.

**Comment by harmo** [comment]
Ok no problem, I'll rename then.

**Comment by tomchristie** [comment]
Cheers. Keeps the responsibility more separate.

**Pull request merged**
