### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by harmo**
Not tested on django < 1.7 & python < 2.7

**update**
DONE

### CODE REVIEW

**Comment by harmo** [comment]
Ouch, I don't see the old versions were supported xD

Trying to fix that right now

**Comment by harmo** [comment]
And ready to go :)

**Comment by tomchristie** [comment]
Looks good. Tho we're no longer accepting pull requests on this repo.
We'd be happy to eg link to your fork as a maintained version.

**Comment by harmo** [comment]
@tomchristie  Ok I'm in :)

**Comment by tomchristie** [comment]
I'd suggest a PR against our README - link at the end of the **Note** section

**Pull request closed without merging**
